name: Django CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Install Dependencies
      run: |
        pwd
        #cd /var/www/zc_plugin_company_sales_prospect/
        git pull origin dev
        source venv/bin/activate
        

        pip install -r requirements.txt
        python manage.py migrate
        python manage.py runserver
    - name: Run Tests
      run: |
        python manage.py test
