name: Django CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v2
 
    - name: Install Dependencies
      run: |
        cd /var/www/zc_plugin_company_sales_prospects/
        git pull origin dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py runserver
    - name: Run Tests
      run: |
        python manage.py test
