name: Company sales Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but for the dev branch
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use cached node_modules
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: react-spa
      - name: Install yarn dependencies and build project
        run: |
          cd react-spa
          yarn install
          yarn build
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd /var/www/zc_plugin_company_sales_prospect/
            git stash
            git pull origin dev
            cd react-spa/
            yarn install
      - name: Copy Main react App folder to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          localPath: './react-spa/'
          remotePath: '/var/www/zc_plugin_company_sales_prospect/react-spa/'

      - name: Copy epictetus folder to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          localPath: './react-spa/epictetus/'
          remotePath: '/var/www/zc_plugin_company_sales_prospect/react-spa/epictetus/'

      
